# Generated by Django 4.2.4 on 2023-08-03 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0002_employeerequest_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerequest',
            name='feedback',
        ),
    ]
