# Generated by Django 4.2.4 on 2023-08-12 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_terms', models.TextField()),
                ('sign_status', models.CharField(choices=[('Pending', 'Pending'), ('Signed', 'Signed'), ('Declined', 'Declined')], default='Pending', max_length=20)),
                ('employee_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='certification.employeerequest')),
            ],
        ),
    ]
