# Generated by Django 4.2.4 on 2023-08-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
