# Generated by Django 4.2.4 on 2023-08-14 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0012_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
